name: Auto Update Red Bull News

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - run: npm install rss-parser
    - name: Jalankan Script Update
      run: node fetch-redbull-news.js
    - name: Commit & Push
      run: |
       git config user.name "github-actions"
       git config user.email "github-actions@github.com"
       git add redbull-news.json || true
       git diff --cached --quiet || git commit -m "Update Red Bull news automatically"
       git stash
       git pull origin main
       git stash pop || true
       git push
