name: 🔄 Update News & Standings

on:
  schedule:
    - cron: '0 */6 * * *'   # Setiap 6 jam
  workflow_dispatch:        # Bisa dijalankan manual

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Fetch Red Bull News
        run: node fetch-redbull-news-puppeteer.js

      - name: Fetch F1 Standings
        run: node fetch-standings-puppeteer.js

      - name: Commit & Push if data changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git diff --quiet redbull-news.json standings.json; then
            echo "✅ Tidak ada perubahan pada JSON. Skip commit."
          else
            git add redbull-news.json standings.json
            git commit -m "🔄 Update Berita Red Bull & Klasemen F1"
            git push
          fi
