name: Update News & Standings

on:
  schedule:
    - cron: '0 */6 * * *'  # Setiap 6 jam sekali
  workflow_dispatch:       # Bisa juga dijalankan manual di tab Actions

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Jalankan Puppeteer untuk berita Red Bull
        run: node fetch-redbull-news-puppeteer.js

      - name: Jalankan Puppeteer untuk klasemen resmi Formula1.com
        run: node fetch-standings-puppeteer.js

      - name: Commit dan Push jika ada perubahan
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git diff --quiet redbull-news.json standings.json; then
            echo "✅ Tidak ada perubahan pada JSON. Skip commit."
          else
            git add redbull-news.json standings.json
            git commit -m "🔄 Update Berita Red Bull & Klasemen F1"
            git push
          fi
